name: cikm
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - backcall=0.2.0=pyhd3eb1b0_0
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py37h06a4308_0
  - debugpy=1.5.1=py37h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py37h06a4308_0
  - ipykernel=6.9.1=py37h06a4308_0
  - ipython=7.31.1=py37h06a4308_1
  - jedi=0.18.1=py37h06a4308_1
  - jupyter_client=7.2.2=py37h06a4308_0
  - jupyter_core=4.10.0=py37h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py37h06a4308_0
  - openssl=1.1.1q=h7f8727e_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.1.2=py37h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pygments=2.11.2=pyhd3eb1b0_0
  - python=3.7.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyzmq=23.2.0=py37h6a678d5_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.2=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py37h27cfd23_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - attrs==22.1.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - boto3==1.24.34
    - botocore==1.27.51
    - cffi==1.15.1
    - charset-normalizer==2.1.0
    - cycler==0.11.0
    - defusedxml==0.7.1
    - dill==0.3.5.1
    - fastjsonschema==2.16.1
    - gensim==4.0.1
    - idna==3.3
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - ipython-genutils==0.2.0
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.1.0
    - jsonschema==4.9.1
    - jupyterlab-pygments==0.2.2
    - kiwisolver==1.4.4
    - lxml==4.9.1
    - markupsafe==2.1.1
    - matplotlib==3.4.3
    - mistune==0.8.4
    - multiprocess==0.70.13
    - nbclient==0.6.6
    - nbconvert==6.5.3
    - nbformat==5.4.0
    - networkx==2.6.3
    - notebook==6.4.12
    - numpy==1.21.6
    - packaging==21.3
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - pathos==0.2.8
    - pillow==9.2.0
    - pkgutil-resolve-name==1.3.10
    - pox==0.3.1
    - ppft==1.7.6.5
    - prometheus-client==0.14.1
    - pyarrow==9.0.0
    - pycparser==2.21
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dotenv==0.20.0
    - python-levenshtein==0.12.2
    - pytz==2022.2.1
    - reclist==0.2.3
    - requests==2.28.1
    - s3transfer==0.6.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sklearn==0.0
    - smart-open==6.0.0
    - soupsieve==2.3.2.post1
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - tqdm==4.62.3
    - traitlets==5.3.0
    - typing-extensions==4.3.0
    - urllib3==1.26.11
    - webencodings==0.5.1
    - wget==3.2
    - zipp==3.8.1
prefix: /home/wei/anaconda3/envs/cikm
